FROM maven:3.6.3-openjdk-8 as builder

# Create app directory
WORKDIR /usr/src/app

COPY ./complete/pom.xml .

RUN mvn dependency:go-offline

COPY ./complete/src ./src

RUN mvn package


ENV APP_NAME test_app

WORKDIR /usr/src/app


#COPY --from=builder /usr/src/app/target/*.jar /usr/src/app/$APP_NAME.jar

EXPOSE 8080

#RUN chmod +x /usr/src/app/target/$APP_NAME.jar
RUN chmod +x /usr/src/app/target/*.jar

CMD java $JAVA_OPTS -jar ./target/*.jar --debug

