version: '3'

services:
    rust_web:
        image: rust-web
        build:
            context: rust-hello-web
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        restart: unless-stopped
        container_name: "rust_web"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.rust.entrypoints=web"
            - "traefik.http.routers.rust.rule=Host(`rust.localhost`)"
    java_web:
        image: java-web
        build:
            context: gs-rest-service-main
            dockerfile: Dockerfile
#            dockerfile: Dockerfile.fat
        ports:
            - 8081:8080
            - 5005:5005
        environment:
            - JAVA_OPT="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
        restart: unless-stopped
        container_name: "java_web"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.java.entrypoints=web"
            - "traefik.http.routers.java.rule=Host(`java.localhost`)"

    go_web:
        image: go-web
        build:
            context: go-hello-web
#            dockerfile: Dockerfile
            dockerfile: Dockerfile.busybox
        ports:
            - 9080:9080
        restart: unless-stopped
        container_name: "go_web"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.go.entrypoints=web"
            - "traefik.http.routers.go.rule=Host(`go.localhost`)"

    whoami:
        image: "traefik/whoami"
        container_name: "whoami"
        ports:
            - 9082:80
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
            - "traefik.http.routers.whoami.entrypoints=web"

