version: '3'

services:
  rust_web:
    image: rust-web
    restart: unless-stopped
#    container_name: "rust_web"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rust.entrypoints=web"
      - "traefik.http.routers.rust.rule=Host(`rust.localhost`)"
  java_web:
    image: java-web
    restart: unless-stopped
#    container_name: "java_web"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.java.entrypoints=web"
      - "traefik.http.routers.java.rule=Host(`java.localhost`)"

  go_web:
      image: go-web
      restart: unless-stopped
#      container_name: "go_web"
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.go.entrypoints=web"
          - "traefik.http.routers.go.rule=Host(`go.localhost`)"

  whoami:
      image: "traefik/whoami"
#      container_name: "whoami"
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
          - "traefik.http.routers.whoami.entrypoints=web"
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
